name: Jonsy
description: Jonsy's landing page
url: "http://flxkrmr.github.io"
markdown: kramdown

title: Jonsy

banner:
  title: Welcome to Jonsy's homepage
  subtitle: Jojojo

info:
  img: foto.jpg
  text: Blablabla

links:
  instagram: http://www.instagram.de
  facebook: www.facebook.de
  spotify: www.spotify.de
  bandcamp: www.bandcamp.de
  youtube: www.youtube.de/ladfkjs
    

