name: Jonsy
description: Jonsy's landing page
url: "http://flxkrmr.github.io"
markdown: kramdown

title: Jonsy
banner:
  title: Welcome to Jonsy's homepage
  subtitle: Jojojo

links:
  instagram: www.instagram.de
  facebook: www.facebook.de
  spotify: www.spotify.de
  bandcamp: www.bandcamp.de
  youtube: www.youtube.de/ladfkjs
    

