name: Jonsy
description: Jonsy's landing page
url: "http://flxkrmr.github.io"
markdown: kramdown

title: Page Title

banner:
  title: Main Title
  subtitle: Jojojo
  img: /assets/img/tree.gif

info:
  img: /assets/img/foto.jpg
  text: Blablabla

links:
  instagram: http://www.instagram.de
  facebook: http://www.facebook.de
  spotify: http://www.spotify.de
  bandcamp: http://www.bandcamp.de
  youtube: http://www.youtube.de/ladfkjs

contact:
  service: http://www.someformservice.com
